fix: check if test exists

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -46,6 +46,11 @@ jobs:
         env:
           APPS_ALL_CHANGED_FILES: ${{ steps.changed-argo-apps.outputs.apps_all_changed_files }}
         run: |
+          if [ ! -f "test/$(basename ${APPS_ALL_CHANGED_FILES} | sed -E 's/-([a-z])/_\1/g') | sed 's/.yaml/_test.go/'" ]; then
+            echo "Test coverage not found. bye!"
+            exit 2
+          fi
+          
           export PATH=$PATH:bin
           echo "List all the files that have changed: $APPS_ALL_CHANGED_FILES"
           go test -v ./test -run $(basename ${APPS_ALL_CHANGED_FILES} .yaml |  sed 's/.*/Test\u&/' | sed -E 's/-([a-z])/\U\1/g')
